name: Docker Release

on:
  push:
    tags:
      - 'nosqlbench-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build nosqlbench docker
        run: cd nb && docker build -t nosqlbench -f ./Dockerfile-build ./
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: nosqlbench/nosqlbench
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_names: true
          dockerfile: Dockerfile
          workdir: nb
