name: CI

on:
  push:
    branches: 
     - testbranch

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12'
        java-package: jdk
        architecture: x64
        
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2   
    - name: read versions
      run: |
        set -x
        CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        RELEASE_VERSION=${CURRENT_VERSION%%-SNAPSHOT}
        BASE_VERSION=$(echo "$RELEASE_VERSION" | cut -d'.' -f1-2)
        MINOR_VERSION=$(echo "$RELEASE_VERSION" | cut -d'.' -f3)
        NEXT_MINOR_VERSION=$(( MINOR_VERSION+1))
        NEXT_SNAPSHOT="${BASE_VERSION}.${NEXT_MINOR_VERSION}-SNAPSHOT"
        echo "::set-env name=NEXT_SNAPSHOT::${NEXT_SNAPSHOT}"
        echo "::set-env name=RELEASE_VERSION::${RELEASE_VERSION}"  
    - name: set git username
      run: git config --global user.email "${{ secrets.NBDROID_EMAIL }}"
    - name: set git email
      run: git config --global user.name "${{ secrets.NBDROID_NAME }}"
    - name: prepare_release
      run: mvn --global-settings deploy.xml --batch-mode clean release:prepare -DdevelopmentVersion=${NEXT_SNAPSHOT} -DreleaseVersion=${RELEASE_VERSION}
    - name: perform_release
      run: mvn --global-settings deploy.xml --batch-mode release:perform
    - name: upload artifacts
      run: mkdir staging && cp nb/target/nb.jar nb/appimage/target/nb staging
    - uses: actions/upload-artifact@v1
      with: 
       name: binaries
       path: staging
    
    - name: upload guidebook
      run: mkdir guidebook && cp -R nb/target/guidebook guidebook
    - uses: actions/upload-artifact@v1
      with:
        name: guidebook
        path: guidebook
